TLoretail/urls.py
from django.contrib import admin
from django.urls import path, include, re_path
from django.conf import settings
from django.conf.urls.static import static
from olretail import views as core_view
from django.views.static import serve
from django.conf.urls.i18n import i18n_patterns


urlpatterns =i18n_patterns (
    path('admin/', admin.site.urls),
    path('', include('olretail.urls')),
    #path('login', core_view.login, name='login'),
    path('accounts/', include('accounts.urls')),
    re_path(r'^media/(?P<path>.*)$', serve, {'document_root':settings.MEDIA_ROOT}),
    path('i18n/', include('django.conf.urls.i18n')),
    prefix_default_language=False,

)+ static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

accounts/urls.py
from .import views as core_view
from django.urls import path

app_name ='accounts'
urlpatterns =[
    path('register/', core_view.register, name='register'),
    path('login/', core_view.userlogin, name ='login'),
    path('logout/', core_view.user_logout, name='logout'),
    path('reset/', core_view.reset, name='reset')

]

accounts/models.py
from django.db import models

# Create your models here.

accounts/views.py
from django.shortcuts import render
from django.contrib.auth.models import User

from olretail.models import Seller, Category
from django.contrib.auth import authenticate, login, logout

from django.contrib.auth.decorators import login_required
from django.shortcuts import redirect
from django.http import HttpResponseRedirect, HttpResponse
from django.contrib.auth.models import Group


def register(request):
    categories = Category.objects.all().order_by('title')
    message=''
    error=False
    if request.method=='POST':
        username = request.POST.get('username')
        email = request.POST.get('email')
        password = request.POST.get('password')
        first_name = request.POST.get('first')
        last_name = request.POST.get('last')
        mobile = request.POST.get('mobile')
        address = request.POST.get('address')

        if User.objects.filter(username=username).exists():
            message='Username already exist'
            error=True
            print("Username already exist")
            return HttpResponse(message)
        else:
            if  User.objects.filter(email=email).exists():
                message='Email is already exist'
                error=True
                print("Email already exist")
                return HttpResponse(message)
            else:
                user = User.objects.create_user(username=username, email=email,password=password,first_name=first_name)
                user.save()
                group = Group.objects.get(name='Seller')
                user.groups.add(group)
                seller = Seller.objects.create(user=user, address=address, mobile=mobile)
                seller.save()
                if user is not None:
                    login(request, user)
                    return HttpResponseRedirect('/seller')
    else:
        return render(request, 'accounts/register.html', {'message':message, 'error':error,'categories':categories})


def userlogin(request):
    categories = Category.objects.all().order_by('title')
    if request.method=='POST':
        username = request.POST.get('username')
        password = request.POST.get('password')
        user = authenticate(username=username, password=password)
        if user is not None:
            login(request, user)
            return HttpResponseRedirect('/seller')
    return render(request, 'accounts/login.html', {'categories':categories})

  
def reset(request):
    categories = Category.objects.all().order_by('title')
    return render(request, 'accounts/reset.html', {'categories':categories})


@login_required
def user_logout(request):
    logout(request)
    return HttpResponseRedirect('/')

accounts/templates/accounts/login.html
{% extends 'shared/base.html' %}
{% load static %}
{% block content %}
<div class="container">
    <div class="row justify-content-center">
      <div class="card m-1">
          <div class="card-header"> <h2 class="text-center mt-1">Please Log In</h2></div>
             
              <form class="bg-white  rounded-5 shadow-5-strong p-5" method="POST" action="{% url 'accounts:login'%}">
                {% csrf_token %}
                <!-- Email input -->
                <div class="form-outline mb-4">
                  <label class="form-label" for="form1Example1">Username: </label>
                  <input type="text" id="form1Example1" class="form-control" name="username" />
        
                </div>
        
                <!-- Password input -->
                <div class="form-outline mb-4">
                  <label class="form-label" for="form1Example2">Password: </label>
                  <input type="password" id="form1Example2" class="form-control" name="password" />
        
                </div>
        
                <!-- 2 column grid layout for inline styling -->
                <div class="row mb-4">
                  <div class="col d-flex justify-content-center">
                    <!-- Checkbox -->
                    <div class="form-check">
                      <input class="form-check-input" type="checkbox" value="" id="form1Example3" checked />
                      <label class="form-check-label" for="form1Example3">
                        Remember me
                      </label>
                    </div>
                  </div>
        
                  <div class="col text-center">
                    <!-- Simple link -->
                    <a href="{% url 'accounts:reset' %}">Forgot password?</a>
                  </div>
                </div>
                <!-- Submit button -->
                <button type="submit" class="btn btn-primary btn-block">Login in</button>
              </form>
            </div>
    </div>
  </div>
{% endblock %}

accounts/templates/accounts/register.html
{% extends 'shared/base.html' %}
{% load static %}
{% block content %}
<div class="container">
  <div class="card-body">
    <div class="card-header text-center">
      <h3 class="text-muted">  Sign Up</h3>
    </div>
    {%if error%}
    <p class="text-danger">{{message}}</p>
    {% endif%}
    <form action="" method="POST">
      {% csrf_token %}
      <div class="md-form mb-5">
        <i class=" prefix grey-text"></i>
        <input type="text" id="orangeForm-name" class="form-control validate" required name="first">
        <label data-error="wrong" data-success="right" for="orangeForm-name">First Name</label>
      </div>
      <div class="md-form mb-5">
        <i class=" prefix grey-text"></i>
        <input type="text" id="orangeForm-name" class="form-control validate" required name="last">
        <label data-error="wrong" data-success="right" for="orangeForm-name">Last Name</label>
      </div>
      <div class="md-form mb-5">
        <i class=" prefix grey-text"></i>
        <input type="email" id="orangeForm-email" class="form-control validate" required name="email">
        <label data-error="wrong" data-success="right" for="orangeForm-email">Your email</label>
      </div>
      <div class="md-form mb-5">
        <i class=" prefix grey-text"></i>
        <input type="text" id="orangeForm-name" class="form-control validate" name="username">
        <label data-error="wrong" data-success="right" for="orangeForm-name">User Name</label>
      </div>
      <div class="md-form mb-4">
        <i class=" prefix grey-text"></i>
        <input type="password" id="orangeForm-pass" class="form-control validate" required name="password">
        <label data-error="wrong" data-success="right" for="orangeForm-pass">Your password</label>
      </div>
      <div class="md-form mb-5">
        <i class=" prefix grey-text"></i>
        <input type="text" id="orangeForm-name" class="form-control validate" required name="address">
        <label data-error="wrong" data-success="right" for="orangeForm-name">Address</label>
      </div>
      <div class="md-form mb-5">
        <i class=" prefix grey-text"></i>
        <input type="text" id="orangeForm-name" class="form-control validate" required name="mobile">
        <label data-error="wrong" data-success="right" for="orangeForm-name">Phone</label>
      </div>
      <div class="d-flex justify-content-center">
        <button class="btn btn-deep-orange">Sign up</button>
      </div>
    </form>
  </div>
</div>


{% endblock %}

accounts/templates/accounts/reset.html
{% extends 'shared/base.html' %}
{% load static %}
{% block content %}
    <h4>Reset Page</h4>
{% endblock %}