TLoretail/urls.py
from django.contrib import admin
from django.urls import path, include, re_path
from django.conf import settings
from django.conf.urls.static import static
from olretail import views as core_view
from django.views.static import serve
from django.conf.urls.i18n import i18n_patterns


urlpatterns =i18n_patterns (
    path('admin/', admin.site.urls),
    path('', include('olretail.urls')),
    #path('login', core_view.login, name='login'),
    path('accounts/', include('accounts.urls')),
    re_path(r'^media/(?P<path>.*)$', serve, {'document_root':settings.MEDIA_ROOT}),
    path('i18n/', include('django.conf.urls.i18n')),
    prefix_default_language=False,

)+ static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

accounts/urls.py
from .import views as core_view
from django.urls import path

app_name ='accounts'
urlpatterns =[
    path('register/', core_view.register, name='register'),
    path('login/', core_view.userlogin, name ='login'),
    path('logout/', core_view.user_logout, name='logout'),
    path('reset/', core_view.reset, name='reset')

]

olretail/urls.py
from .views import (
    IndexView, LoginView, DetailsView, ListaView,CategoryView
) 
from .import views as core_view
from django.urls import path

app_name='olretail'

urlpatterns =[
    path('', IndexView.as_view(), name='index' ),
    path('login/', LoginView.as_view(), name ='login'),
    path('seller/create-product/', core_view.CreateNewProduct, name='create_product'),
    path('seller/update-product/<slug:slug>', core_view.UpdateProduct, name='update_product'),
   # path('create_product/<int:id>', core_view.CreateNewProduct, name='create'),
    path('details/<slug:slug>/', DetailsView.as_view(), name='details'),
    path('seller/', core_view.listView, name='list'),
    #path('user_login/', core_view.user_login, name='user_login'),
    #path('userlogout/', core_view.user_logout, name='log_out'),
    path('category/<int:id>', CategoryView.as_view(), name='category' ),
    path('search/', core_view.searchView, name='search'),
    path('details/<slug:slug>', core_view.searchView, name='details-search'),
    path('comments/', core_view.comment, name='add-comments'),
]

olretail/models.py
from django.db import models
from django.contrib.auth.models import User
from django.db.models.signals import post_save
from django.dispatch import receiver
from django.contrib.auth.models import UserManager
from django.contrib.auth.models import AbstractUser

from django.utils.text import slugify

condition =(
    ("New", "New"),
    ("Second Hand", "Second Hand")

)

class Buyer(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE)
    address = models.CharField(max_length=40)
    mobile = models.CharField(max_length=40)


    @property
    def get_name(self):
        return self.user.first_name+" "+self.user.last_name

    @property
    def get_id(self):
        return self.user.id

    def __str__(self):
        return self.user.first_name


class Seller(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE)
    address = models.CharField(max_length=40)
    mobile = models.CharField(max_length=20, null=False)
   

    @property
    def get_name(self):
        return self.user.first_name+" "+self.user.last_name

    @property
    def get_id(self):
        return self.user.id

    def __str__(self):
        return self.user.first_name

"""
Class Address
"""
class Country(models.Model):
    country = models.CharField(max_length=100, unique=True)

    def __str__(self):
        return self.country

'''City Class'''
class City(models.Model):
    city = models.CharField(max_length=100, unique=True)
    country = models.ForeignKey(Country, on_delete=models.CASCADE)

    def __str__(self):
        return self.city


'''Category class'''
class Category(models.Model):
    title = models.CharField(max_length=200)
    slug = models.SlugField(unique=True)

    def __str__(self):
        return self.title

'''Product Class'''
class Product(models.Model):
    name = models.CharField(max_length=200)
    slug = models.SlugField()
    product_image = models.ImageField(
        upload_to='product_image', null=True, blank=True)
    product_image_2 = models.ImageField(upload_to='product_image', blank=True, default=True)
    product_image_3 = models.ImageField(upload_to='product_image', blank=True, default=True)
    category = models.ForeignKey(
        Category, on_delete=models.CASCADE, blank=True)
    price = models.DecimalField(max_digits=13, decimal_places=2)
    description = models.TextField()
    country = models.ForeignKey(Country, on_delete=models.CASCADE, default=True)
    item_location = models.ForeignKey(
        City, on_delete=models.CASCADE, blank=True)
    created = models.DateTimeField(auto_now_add=True)
    updated = models.DateTimeField(auto_now=True)
    quantity = models.PositiveIntegerField()
    seller = models.ForeignKey(Seller, on_delete=models.CASCADE)
    approved = models.BooleanField(default=False)
    condition = models.CharField(max_length=40, choices=condition, default=True)

    #status = models.CharField()
    def save(self, *args, **kwargs):
        self.slug = slugify(self.name)
        super(Product, self).save(*args, **kwargs)
    def __str__(self):
        return self.name

'''Comment Area'''
class Comment(models.Model):
    product = models.ForeignKey(Product, on_delete= models.CASCADE, default=True)
    commenter_name = models.CharField(max_length=200)
    coment_body  = models.TextField()
    date_added = models.DateTimeField(auto_now=True)

    def __str__(self):
       return '%s - %s' %(self.product, self.commenter_name)

olretail/forms.py
from django import forms
from .models import Product
from django.contrib.auth import login, authenticate

from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth.models import User
from .models import Seller, Product, Comment



#---------------Seller user form

class SellerUserForm(forms.ModelForm):
    password =forms.CharField(widget=forms.PasswordInput())
    class Meta:
        model = User

        def get_username(self):
            self.username= self.first_name
            return self.username

        fields =['first_name','last_name','username', 'email', 'password']

        def __init__(self, *args, **kwargs):
            super(SellerUserForm, self).__init__(*args, **kwargs)
            self.fields['username'].required =False


#---------------Seller form
class SellerForm(forms.ModelForm):
    class Meta:
        model = Seller
        fields =('address', 'mobile')


#-------------------Product form

class ProductForm(forms.ModelForm):
    class Meta:
        model = Product
        fields=('name', 'product_image', 
                'category','price', 'description',
                'country','item_location','quantity', 'condition'
                )
        #labels ={
        #    'name':'Product Name',
        #    'item_location':'City',
        #    'seller' :'Name'
        #}

    # def __init__(self,*args, **kwargs):
       
    #     super(ProductForm,self).__init__(*args, **kwargs)
    #     #user=User.objects.get(user_id=self.seller)
    #     self.fields['category'].empty_label='Select Category'
    #     self.fields['item_location'].empty_label='Select City'
    #     self.fields['country'].empty_label ='Select Country'
    #     self.fields['quantity'].required = False
     
class CommentForm(forms.ModelForm):
    class Meta:
        model=Comment
        fields='__all__'

 

olretail/views.py
from django.shortcuts import render
from django.views.generic import TemplateView
from django.views.generic.detail import DetailView
from django.views.generic.edit import CreateView
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth.models import User
from django.urls import reverse
from django.db.models import Sum
from django.contrib.humanize.templatetags.humanize import intcomma


from .decorators import *
from django.contrib import messages

#-------Import Models
from .models import Product, Seller, Category, Country, City, Comment
#------------import forms
from .forms import SellerUserForm, SellerForm, ProductForm, CommentForm

from django.contrib.auth import authenticate, login, logout
from django.http import HttpResponseRedirect, HttpResponse

from django.contrib.auth.decorators import login_required
#--------User Group

from django.contrib.auth.models import Group

#--------- import Paginator
from django.core.paginator import Paginator

# Create your views here.


class IndexView(TemplateView):
    template_name = 'olretail/index.html'
    paginate_by = 2

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        category = self.request.GET.get('category')
        if category == None:
            context['product'] = Product.objects.all().order_by('-price')
        else:
            context['product'] = Product.objects.filter(
                category__slug=category)
        context['categories'] = Category.objects.all().order_by('title')
        return context


class DetailsView(TemplateView):
    template_name = 'olretail/details.html'

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        slug = self.kwargs['slug']
        details = Product.objects.get(slug=slug)
        context['details'] = details
        context['categories'] = Category.objects.all().order_by('title')
        context['comments'] = Comment.objects.all()
        return context


class CategoryView(TemplateView):
    template_name = 'olretail/category.html'

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        cat = Category.objects.all()
        context['product'] = Product.objects.all()
        return context


class LoginView(TemplateView):
    template_name = 'olretail/login.html'

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['product'] = Product.objects.all().order_by('-price')
        context['categories'] = Category.objects.all().order_by('title')
        return context


class RegisterView(TemplateView):
    template_name = 'olretail/register.html'

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['product'] = Product.objects.all().order_by('-price')
        context['categories'] = Category.objects.all().order_by('title')
        return context


class ListaView(TemplateView):
    template_name = 'olretail/lista.html'

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)

        context['product'] = Product.objects.all().order_by('id')
        context['categories'] = Category.objects.all().order_by('title')
        return context


def searchView(request):
    categories = Category.objects.all().order_by('title')
    if request.method == 'GET':
        search_item = request.GET.get('search')
        print(search_item)
        if search_item:
            product = Product.objects.filter(name__contains=search_item)
            print(product)
            return render(request, 'olretail/search.html', context={'product': product, 'categories': categories})
        else:
            print("No search found")
            return render(request, 'olretail/search.html', {'categories': categories})


@login_required(login_url='/accounts/login/')
@allowed_users(allowed_roles=['Seller'])
def listView(request):
    categories = Category.objects.all().order_by('title')
    product_list = request.user.seller.product_set.all()
    count = len(product_list)
    total_price = request.user.seller.product_set.all().aggregate(Sum('price'))['price__sum']
    total_price = f"$ {intcomma('{:0.2f}'.format(total_price))}"
    print(total_price)
    return render(request, 'olretail/lista.html', context={'product_list': product_list, 'categories': categories, 'count': count, 'total': total_price})


#-----Seller sign form
'''''
def SellersignupView(request):
    categories = Category.objects.all().order_by('title')
    registered = False
    if request.method == 'POST':
        userForm = SellerUserForm(data=request.POST)
        sellerForm = SellerForm(data=request.POST)
        if userForm.is_valid() and sellerForm.is_valid():
            user = userForm.save()
            user.set_password(user.password)
            user.save()
            group = Group.objects.get(name='Seller')
            user.groups.add(group)
            seller = sellerForm.save(commit=False)
            seller.user = user
            seller.save()
            registered = True
            login(request, user)
            messages.success(request, "Registration user successfull.")
            return HttpResponseRedirect('/list')
        messages.error(
            request, "Unsuccessful registration. Invalid Information")

    else:
        userForm = SellerUserForm()
        sellerForm = SellerForm()

    return render(request, 'olretail/signup.html', context={'userForm': userForm, 'sellerForm': sellerForm, 'categories': categories})

'''''
#--------------------Product form


@login_required(login_url='/accounts/login/')
@allowed_users(allowed_roles=['Seller'])
def CreateNewProduct(request):
    cat = Category.objects.all()
    count = Country.objects.all()
    city = City.objects.all()
    successfull = False
    seller_id = request.user.id
    print("seller name", seller_id)
    product_form = ProductForm()
    if request.method == 'POST':
        print("seller within post", seller_id)
        name = request.POST.get('product')
        price = request.POST.get('price')

        image = request.FILES.get('image')
        category = request.POST.get('category')
        country = request.POST.get('country')
        city = request.POST.get('city')
        quantity = request.POST.get('quantity')
        description = request.POST.get('description')
        condition = request.POST.get('condition')
        user_id = request.user.id
        categ = Category.objects.get(id=category)
        countries = Country.objects.get(id=country)
        cities = City.objects.get(id=city)
        seller = Seller.objects.get(user_id=user_id)
        print("user id :", seller, "and")

        product_form = Product.objects.create(name=name,
                                              price=price,
                                              product_image=image,
                                              category=categ,
                                              country=countries,
                                              item_location=cities,
                                              quantity=quantity,
                                              description=description,
                                              seller=seller,
                                              condition=condition,
                                              )
        print("Image product", product_form.product_image)

        #product_form = ProductForm(request.POST,seller, request.FILES)
        #if product_form.is_valid():
        product_form.save()
        successfull = True
        return HttpResponseRedirect('/seller')
    else:
        print('Error in input data', product_form)
    return render(request, 'olretail/products.html',
                  context={'product_form': product_form,
                           'successfull': successfull,
                           'cat': cat,
                           'count': count,
                           'city': city
                           }
                  )
@login_required(login_url='/accounts/login/')
@allowed_users(allowed_roles=['Seller'])
def UpdateProduct(request, slug):
    product = Product.objects.get(slug=slug)
    print(product.name)
    print(product.price)
    form = ProductForm(instance=product)
    print(product)
    return render(request, 'olretail/products_update.html', context={'form':form})
def comment(request):
    form=CommentForm()
    if request.method=='POST':
        form = CommentForm()
    return render(request, 'olretail/comments.html', {'form':form})

'''''
@login_required
def user_logout(request):
    logout(request)
    return HttpResponseRedirect('/')


def user_login(request):
    categories = Category.objects.all().order_by('title')
    if request.method == 'POST':
        username = request.POST.get('username')
        password = request.POST.get('password')
        user = authenticate(username=username, password=password)

        if user:
            if user.is_active:
                login(request, user)
                messages.info(request, f"You are now logged in as {username}.")
                return HttpResponseRedirect('/seller')
            else:
                messages.error(request, 'Account is disabled or not active')
        else:
            messages.error(request, "Invalid username or password.")
    return render(request, 'olretail/login.html', {'categories': categories})
'''''

templates/olretail/category.html
{% extends 'shared/base.html' %}
{% load static %}
{% block content %}
 <h1>Category by Product</h1>
 {%for pr in product %}
 {{pr.category}}
 {% endfor %}
{% endblock %}

templates/olretail/comments.html
{%extends 'shared/base.html'%}
{% block content %}
<form action="POST">

    {{form}}
    <input type="button"  class="btn btn-success" value="Submit Comment">
</form>
{% endblock %}

templates/olretail/index.html
{% extends 'shared/base.html' %}
{% load i18n %}
{% load static %}
{% block content %}
<div class="container-xl">
        <!--Grid Row-->
        <div class="row">
                <div class="col-md-8 col-lg-10 col-xl-9">
                        {% include 'shared/slider.html'%}
                        <section class="py-2 my-4">
                                <div class="divider-new version-2 mt-5 mb-0">
                                        <h4 class="text-uppercase font-weight-bold deep-grey-text mr-3 text-danger">{%trans 'New arrival'%}</h4>
                                </div>
                                <!--Product Section-->
                                <div class="row pt-4">
                                        {% for products in product%}
                                        {%if products.approved%}
                                        <div class="col mb-4 mb-xl-0 ">

                                                <div class="view zoom overlay">
                                                        <img class="img-fluid w-10" src="{{products.product_image.url}}"
                                                                alt="Sample">
                                                        <a href="{% url 'olretail:details' products.slug%}">
                                                                <div class="mask">
                                                                </div>
                                                        </a>
                                                </div>
                                                <div class="pt-4">

                                                        <p class="mb-2 text-muted text-uppercase small">
                                                                {{products.name}}</p>
                                                        <!-- <h6 class="mb-0"><span class="badge badge-danger badge-pill">-20%</span></h6> -->
                                                        <span>
                                                                <strong>$ {{products.price}}</strong>
                                                        </span>
                                                        <br>
                                                        <span>
                                                                <strong>{{products.category.title}}</strong>
                                                        </span>
                                                        <br>
                                                        <!-- <span>
                                                                Product owner: <strong>{{pr.seller.user.first_name}} {{pr.seller.user.last_name}} </strong>
                                                        </span> -->
                                                </div>

                                        </div>
                                        {%endif%}
                                        {% endfor %}
                                </div>
                        </section>
                        <!--Product Section-->

                        <!-- Section apparel -->
                        {% trans "let's transale this one"%}
                        <div class="divider-new version-2 mt-5 mb-0">
                                <h4 class="text-uppercase font-weight-bold deep-grey-text mr-3 text-danger">{% trans 'Flash Deals / SalesOn !!!' %}</h4>
                        </div>
                        <!-- Section electronics -->
                        <section class="py-2 my-4">

                                <div class="row">
                                        <div class="col-12">

                                                <div class="card">
                                                        <div class="card-body">

                                                                <div
                                                                        class="row row-cols-1 row-cols-md-2 row-cols-lg-2 row-cols-xl-4">
                                                                        {%for products in product%}
                                                                        <div class="col mb-4 pb-2">
                                                                                <div class="view zoom overlay">
                                                                                        <h5 class="mt-0"><a
                                                                                                        href="{% url 'olretail:details' products.slug%}"
                                                                                                        class="text-reset stretched-link">{{products.name}}</a>
                                                                                        </h5>
                                                                                        <img class="float-right"
                                                                                                src="{{products.product_image.url}}"
                                                                                                alt="Sample"
                                                                                                width="110">
                                                                                        <p><i class="fa fa-map-marker-alt"></i>
                                                                                                {{products.item_location}},
                                                                                                {{products.country}}
                                                                                        </p>
                                                                                </div>
                                                                        </div>
                                                                        {% endfor %}

                                                                </div>

                                                        </div>
                                                </div>

                                        </div>
                                </div>

                        </section>
                        <!-- Section electronics -->
                        <!-- Section electronics -->
                        <div class="divider-new version-2 mt-5 mb-0">
                        <h4 class="text-uppercase font-weight-bold deep-grey-text mr-3 text-danger">{% trans 'Discount or Promotion'%}</h4>
                        </div>
                        <section class="py-2 my-4">

                                <div class="row">
                                        <div class="col-12">

                                                <div class="card">
                                                        <div class="card-body">

                                                                <div
                                                                        class="row row-cols-1 row-cols-md-2 row-cols-lg-2 row-cols-xl-4">

                                                                        {%for products in product%}
                                                                        <div class="col mb-4 pb-2">
                                                                                <div class="view zoom overlay">
                                                                                        <h5 class="mt-0"><a
                                                                                                        href="{% url 'olretail:details' products.slug%}"
                                                                                                        class="text-reset stretched-link">{{products.name}}</a>
                                                                                        </h5>
                                                                                        <img class="float-right"
                                                                                                src="{{products.product_image.url}}"
                                                                                                alt="Sample"
                                                                                                width="110">
                                                                                        <p><i class="fa fa-map-marker-alt"></i>
                                                                                                {{products.item_location}},
                                                                                                Timor Leste
                                                                                        </p>
                                                                                </div>
                                                                        </div>
                                                                        {% endfor %}

                                                                </div>

                                                        </div>
                                                </div>

                                        </div>
                                </div>

                        </section>
                        <!-- Section electronics -->
                </div>
                <div class="col-md-5  col-lg-2 col-xl-3">
                        {% include 'shared/popular_category.html'%}
                </div>
                <!-- {% include 'shared/my_market.html' %}-->

        </div>
</div>
{% endblock %}

templates/olretail/lista.html
{% extends 'shared/base.html' %}

{% load static %}
{% block content %}


<div class="container">
  <div class="row">
    <div class="col-md-4 m-1">

      <div class="card">
        <div class="card-header text-danger text-center">
          <h2>Total Product on sale</h2>
        </div>
        <div class="card-body text-center">
          <h2>Total</h2>
          <p class="text-muted">{{count}}</p>
        </div>
      </div>
    </div>
    <div class="col-md-4 m-1">

      <div class="card">
        <div class="card-header text-danger text-center">
          <h2>Total Product sold</h2>
        </div>
        <div class="card-body text-center">
          <h2>Total</h2>
          <p class="text-muted">{{total}}</p>
        </div>
      </div>
    </div>

  </div>

  <table class="table">
    <thead>
      <tr>
        <th scope="col">Number</th>
        <th scope="col">Name</th>
        <th scope="col">Price</th>
        <th scope="col">Status</th>
        <th scope="col">Product info</th>
        <th scope="col">Action</th>
      </tr>
    </thead>
    <tbody>

      {% for products in product_list%}
      <tr>
        <th scope="row">{{forloop.counter}}</th>
        <td>{{products.name}}</td>
        <td>{{products.price |stringformat:".2f"}}</td>
        {% if products.approved%}
        <td>Already Post</td>
        {% else %}
        <td>Request for Approval</td>
        {% endif %}
        <td>{{products.condition}}</td>
        <td><a href="{% url 'olretail:update_product' products.slug%}" class=""><i class="fas fa-edit"></i></a></td>
      </tr>
      {%endfor%}
    </tbody>
    <tfoot>
      <tr>
          <th colspan="2" style="text-align: center;"> <h3>Total</h3></th>
          <td>{{total}}</td>
          <td> </td>
          <td></td>
      </tr>
  </tfoot>
  </table>
</div>


<!-- Modal -->


{% endblock %}

templates/olretail/password_reset.html
<div class="container p-5">
    <h2 class="font-weight-bold mt-3">Reset Password</h2>
 <hr>
 <p>Forgotten your password? Enter your email address below, and we'll email instructions for setting a new one.</p>
 <form method="POST">
     {% csrf_token %}
     {{ password_reset_form|crispy }}                    
     <button class="btn btn-primary" type="submit">Send email</button>
 </form>
</div> 

templates/olretail/search.html
{% extends 'shared/base.html' %}
{% load static %}
{% block content %}
<div class="container">
        <section class="py-2 my-4">
                <div class="row pt-4">
                        {% for products in product%}
                        {%if products.approved%}
                        <div class="col-md-4 mb-4 mb-xl-0 ">

                                <div class="view zoom overlay">
                                        <img class="img-fluid w-100" src="{{products.product_image.url}}" alt="Sample">
                                        <a href="{% url 'olretail:details' products.slug %}">
                                                <div class="mask">
                                                </div>
                                        </a>
                                </div>
                                <div class="pt-4">

                                        <p class="mb-2 text-muted text-uppercase small">{{products.name}}</p>
                                        <!-- <h6 class="mb-0"><span class="badge badge-danger badge-pill">-20%</span></h6> -->
                                        <span>
                                                <strong>$ {{products.price}}</strong>
                                        </span>
                                        <br>
                                        <span>
                                                <strong>{{products.category.title}}</strong>
                                        </span>
                                        <br>
                                        <!-- <span>
                                                    Product owner: <strong>{{pr.seller.user.first_name}} {{pr.seller.user.last_name}} </strong>
                                            </span> -->
                                </div>

                        </div>
                        {% else %}
                        <h2 class="text-center text-muted">No Product found</h2>
                        {%endif%}

                        {% endfor %}
                </div>
        </section>
</div>
{% endblock %}