TLoretail/urls.py
from django.contrib import admin
from django.urls import path, include, re_path
from django.conf import settings
from django.conf.urls.static import static
from olretail import views as core_view
from django.views.static import serve
from django.conf.urls.i18n import i18n_patterns


urlpatterns =i18n_patterns (
    path('admin/', admin.site.urls),
    path('', include('olretail.urls')),
    #path('login', core_view.login, name='login'),
    path('accounts/', include('accounts.urls')),
    re_path(r'^media/(?P<path>.*)$', serve, {'document_root':settings.MEDIA_ROOT}),
    path('i18n/', include('django.conf.urls.i18n')),
    prefix_default_language=False,

)+ static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

accounts/urls.py
from .import views as core_view
from django.urls import path

app_name ='accounts'
urlpatterns =[
    path('register/', core_view.register, name='register'),
    path('login/', core_view.userlogin, name ='login'),
    path('logout/', core_view.user_logout, name='logout'),
    path('reset/', core_view.reset, name='reset')

]

olretail/urls.py
from .views import (
    IndexView, LoginView, DetailsView, ListaView,CategoryView
) 
from .import views as core_view
from django.urls import path

app_name='olretail'

urlpatterns =[
    path('', IndexView.as_view(), name='index' ),
    path('login/', LoginView.as_view(), name ='login'),
    path('seller/create-product/', core_view.CreateNewProduct, name='create_product'),
    path('seller/update-product/<slug:slug>', core_view.UpdateProduct, name='update_product'),
   # path('create_product/<int:id>', core_view.CreateNewProduct, name='create'),
    path('details/<slug:slug>/', DetailsView.as_view(), name='details'),
    path('seller/', core_view.listView, name='list'),
    #path('user_login/', core_view.user_login, name='user_login'),
    #path('userlogout/', core_view.user_logout, name='log_out'),
    path('category/<int:id>', CategoryView.as_view(), name='category' ),
    path('search/', core_view.searchView, name='search'),
    path('details/<slug:slug>', core_view.searchView, name='details-search'),
    path('comments/', core_view.comment, name='add-comments'),
]

templates/shared/base.1.html
<!DOCTYPE html>
{% load static %}
<html lang="en">

<head>
  <meta charset="UTF-8" />
  <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no" />
  <meta http-equiv="x-ua-compatible" content="ie=edge" />
  <title>Timor Online Retail </title>
<!-- Roboto Font -->
<link rel="stylesheet" href="https://fonts.googleapis.com/css?family=Roboto:100,300,400,500,700&display=swap">
<!-- Font Awesome -->
<link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.11.2/css/all.css">
<!-- Bootstrap core CSS -->
<link rel="stylesheet" href="{% static 'costumize/css/bootstrap.min.css' %}">
<!-- Material Design Bootstrap -->
<link rel="stylesheet" href="{% static 'costumize/css/mdb-pro.min.css' %}">
<!-- Material Design Bootstrap Ecommerce -->
<link rel="stylesheet" href="{% static 'costumize/css/mdb.ecommerce.min.css' %}">
<style>
  @media (min-width: 1100px) {
    .container-xl {
      max-width: 1480px;
    }
  }

  .divider-new.version-2 {
    justify-content: left;
  }

  .divider-new.version-2:before {
    flex: 0;
  }
</style>

</head>

</head>

<body class="skin-light">
  <!--Start navbar here-->
  {% include 'shared/header.1.html' %}
  
  <!--End navbar here-->
  <!-- Start your project here-->
  {% block content %}
  

  {% endblock %}
  <!-- End your project here-->

  <!-- MDB -->

  <!--Start footer-->
  {% include 'shared/footer.html' %}
  <!--End footer-->
<!-- SCRIPTS -->
  <!-- JQuery -->
  <script type="text/javascript" src="{% static 'costumize/js/jquery-3.4.1.min.js' %}"></script>
  <!-- Bootstrap tooltips -->
  <script type="text/javascript" src="{% static 'costumize/js/popper.min.js' %}"></script>
  <!-- Bootstrap core JavaScript -->
  <script type="text/javascript" src="{% static 'costumize/js/bootstrap.min.js'  %}"></script>
  <!-- MDB core JavaScript -->
  <script type="text/javascript" src="{% static 'costumize/js/mdb.min.js' %}"></script>
    <!-- MDB Ecommerce JavaScript -->
    <script type="text/javascript" src="{% static 'costumize/js/mdb.ecommerce.min.js'%}"></script>
  <!-- Your custom scripts (optional) -->
  <script type="text/javascript">
    $(function () {
      $('.material-tooltip-main').tooltip({
        template: '<div class="tooltip md-tooltip-main"><div class="tooltip-arrow md-arrow"></div><div class="tooltip-inner md-inner-main"></div></div>'
      });
    });

    $(document).ready(function () {
      $('.mdb-select').materialSelect();
      $('.select-wrapper.md-form.md-outline input.select-dropdown').bind('focus blur', function () {
        $(this).closest('.select-outline').find('label').toggleClass('active');
        $(this).closest('.select-outline').find('.caret').toggleClass('active');
      });
    });
  </script>

 
</body>

</html>

templates/shared/base.html
<!DOCTYPE html>
{% load static %}
{% load i18n %}
<html lang="en">

<head>
  <meta charset="UTF-8" />
  <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no" />
  <meta http-equiv="x-ua-compatible" content="ie=edge" />
  <title>Timor Online Retail </title>
<!-- Roboto Font -->
<link rel="stylesheet" href="https://fonts.googleapis.com/css?family=Roboto:100,300,400,500,700&display=swap">
<!-- Font Awesome -->
<link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.11.2/css/all.css">
<!-- Bootstrap core CSS -->
<link rel="stylesheet" href="{% static 'costumize/css/bootstrap.min.css' %}">
<!-- Material Design Bootstrap -->
<link rel="stylesheet" href="{% static 'costumize/css/mdb-pro.min.css' %}">
<!-- Material Design Bootstrap Ecommerce -->
<link rel="stylesheet" href="{% static 'costumize/css/mdb.ecommerce.min.css' %}">
<style>
  @media (min-width: 1100px) {
    .container-xl {
      max-width: 1480px;
    }
  }

  .divider-new.version-2 {
    justify-content: left;
  }

  .divider-new.version-2:before {
    flex: 0;
  }
</style>

</head>

</head>

<body class="skin-light">
  <!--Start navbar here-->
  {% include 'shared/header.html' %}
  
  <!--End navbar here-->
  <!-- Start your project here-->
  {% block content %}
  

  {% endblock %}
  <!-- End your project here-->

  <!-- MDB -->

  <!--Start footer-->
  {% include 'shared/footer.html' %}
  <!--End footer-->
<!-- SCRIPTS -->
  <!-- JQuery -->
  <script type="text/javascript" src="{% static 'costumize/js/jquery-3.4.1.min.js' %}"></script>
  <!-- Bootstrap tooltips -->
  <script type="text/javascript" src="{% static 'costumize/js/popper.min.js' %}"></script>
  <!-- Bootstrap core JavaScript -->
  <script type="text/javascript" src="{% static 'costumize/js/bootstrap.min.js'  %}"></script>
  <!-- MDB core JavaScript -->
  <script type="text/javascript" src="{% static 'costumize/js/mdb.min.js' %}"></script>
    <!-- MDB Ecommerce JavaScript -->
    <script type="text/javascript" src="{% static 'costumize/js/mdb.ecommerce.min.js'%}"></script>
  <!-- Your custom scripts (optional) -->
  <script type="text/javascript">
    $(function () {
      $('.material-tooltip-main').tooltip({
        template: '<div class="tooltip md-tooltip-main"><div class="tooltip-arrow md-arrow"></div><div class="tooltip-inner md-inner-main"></div></div>'
      });
    });

    $(document).ready(function () {
      $('.mdb-select').materialSelect();
      $('.select-wrapper.md-form.md-outline input.select-dropdown').bind('focus blur', function () {
        $(this).closest('.select-outline').find('label').toggleClass('active');
        $(this).closest('.select-outline').find('.caret').toggleClass('active');
      });
    });
  </script>

 
</body>

</html>

templates/shared/footer.html
<footer class="text-center text-white" style="background-color: #f1f1f1;">
        <!-- Grid container -->
        <div class="container-xl pt-4">
          <!-- Section: Social media -->
          <section class="mb-4">
            <!-- Facebook -->
            <a
              class="btn btn-link btn-floating btn-lg text-dark m-1"
              href="#!"
              role="button"
              data-mdb-ripple-color="dark"
              ><i class="fab fa-facebook-f"></i
            ></a>
      
            <!-- Twitter -->
            <a
              class="btn btn-link btn-floating btn-lg text-dark m-1"
              href="#!"
              role="button"
              data-mdb-ripple-color="dark"
              ><i class="fab fa-twitter"></i
            ></a>
      
            <!-- Google -->
            <a
              class="btn btn-link btn-floating btn-lg text-dark m-1"
              href="#!"
              role="button"
              data-mdb-ripple-color="dark"
              ><i class="fab fa-google"></i
            ></a>
      
            <!-- Instagram -->
            <a
              class="btn btn-link btn-floating btn-lg text-dark m-1"
              href="#!"
              role="button"
              data-mdb-ripple-color="dark"
              ><i class="fab fa-instagram"></i
            ></a>
      
            <!-- Linkedin -->
            <a
              class="btn btn-link btn-floating btn-lg text-dark m-1"
              href="#!"
              role="button"
              data-mdb-ripple-color="dark"
              ><i class="fab fa-linkedin"></i
            ></a>
            <!-- Github -->
            <a
              class="btn btn-link btn-floating btn-lg text-dark m-1"
              href="#!"
              role="button"
              data-mdb-ripple-color="dark"
              ><i class="fab fa-github"></i
            ></a>
          </section>
          <!-- Section: Social media -->
        </div>
        <!-- Grid container -->
      
        <!-- Copyright -->
        <div class="text-center text-dark p-3" style="background-color: rgba(0, 0, 0, 0.2);">
          © 2021 Copyright:
          <a class="text-dark" href="#">Timor Leste online retail</a>
        </div>
        <!-- Copyright -->
</footer>

templates/shared/header.1.html
<header>

    <!-- Header -->
    <div class="jumbotron white border-bottom mb-0">
        <div class="container-xl py-2">

            <!-- Grid row -->
            <div class="row align-items-center">

                <!-- Grid column -->
                <div class="col-lg-3 col-xl-2 mt-3 mt-lg-0">
                    <a href="{% url 'olretail:index'%}">
                        <img src="/static/mdb/img/logo_ortl.jpeg" height="60">
                    </a>
                </div>
                <!-- Grid column -->

                <!-- Grid column -->
                <div class="col-md-7 col-lg-5 col-xl-6">

                </div>
                <!-- Grid column -->

                <!-- Grid column -->
                <div class="col-md-5 col-lg-4 col-xl-4 mt-2 mb-1 mb-md-0 pb-2 pb-md-0">

                    <!-- Icons -->
                    <div class="d-flex justify-content-start justify-content-md-end text-center">
                            <div class="col-md col-lg-4 col-xl-4 mt-2 mb-1 mb-md-0 pb-2 pb-md-0">
                                {%if user.is_authenticated %}
                                <a href="{% url 'olretail:log_out'%}">
                                    <small class="text-dark"> Logout</small>
                                </a>
                                {% else %}
                                <a href="{% url 'olretail:user_login'%}">
                                    <small class="text-dark"> Login</small>
                                </a>
                                {% endif %}
                            </div>
                            <div class="mr-4">
                                <a href="{% url 'olretail:list'%}">
                                    <!--  <div>
                                        <i class="fas fa-user fa-lg text-muted"></i>
                                                                <span
                                                                    class="counter counter-floating counter-lg-icon position-absolute ml-n1 mt-1"><strong>3</strong></span>
                                                            </div> -->
                                    <small class="text-success">Welcome <strong>{{user.first_name}} {{user.last_name}}</strong> </small>
                                </a>
                            
                            </div>
                    </div>
                    <!-- Icons -->

                </div>
                <!-- Grid column -->

            </div>
            <!-- Grid row -->

        </div>
    </div>
    <!-- Header -->

    <!-- Navbar -->
 
    <!-- Navbar -->

</header>

templates/shared/header.html
{% load i18n %}
<header>
    <div class="container-xl">  <div class="row jumbotron white border-bottom mb-0">
            <div class="col-md-2 m-1">
                <!-- Grid column -->
                    <a href="{% url 'olretail:index'%}">
                        <img src="/static/mdb/img/logo_ortl.jpeg" height="60">
                    </a>
                <!-- Grid column -->
            </div>
            <div class="col-md-5">
                <!-- Grid column -->
    
                <form action="{% url 'olretail:search' %}" method="get">
    
                    <div class="md-form md-outline input-group md-input-group w-100">
    
                        <!-- <div class="select-outline">
                            <select class="mdb-select md-form md-outline my-0">
                                <option value="">All type</option>
                                <option value="codex">Special</option>
                                <option value="comments">Only best</option>
                                <option value="content">Latest</option>
                            </select>
                        </div> -->
    
                        <input type="text" class="form-control mb-0" name="search" placeholder='{%trans "Search by product"%}''>
    
                        <div class="input-group-append">
                            <button class="btn btn-primary btn-md px-3" type="submit">
                                <i class="fa fa-search"></i>{% trans 'Search'%} 
                            </button>
                        </div>
                        <div>
    
                        </div>
                    </div>
    
                </form>
                <!-- Grid column -->
            </div>
            <div class="col-md-4 mt-4 ">
                <!-- Icons -->
                    {%if user.is_authenticated %}
                        
                        <!-- <a href="{% url 'olretail:list'%}">
                            <small class="text-success">Welcome <strong>{{user.first_name}} {{user.last_name}}</strong></small>
                        </a>
                        <a href="{% url 'accounts:logout'%}"><small class="text-success"> Logout</small>
                        </a> -->
                        {% else %}
                        <a href="{% url 'accounts:login'%}">
                            <small class="text-dark">{% trans 'Sign in'%} </small>
                        </a>
                        |
                        <a href="{%url 'accounts:register'%}">
                            <small class="text-dark">{%trans 'Sign up'%} </small>
                        </a>
                        {% endif %}
    
                </div>
        </div></div>

    <nav class="navbar navbar-expand-lg sticky-top navbar-light">

        <div class="container-xl">

            <!-- Collapse button -->
            <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#basicExampleNav1"
                aria-controls="basicExampleNav1" aria-expanded="false" aria-label="Toggle navigation">
                <span class="navbar-toggler-icon"></span>
            </button>

            <!-- Links -->
            <div class="collapse navbar-collapse" id="basicExampleNav1">

                <!-- Left -->
                <ul class="navbar-nav align-items-start">
                    {%if user.is_authenticated %}
                    <li class="nav-item">
                        <a class="nav-link" href="{% url 'olretail:create_product'%}">Create new Product</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" href="{% url 'olretail:list'%}">Your Product List</a>
                    </li>
                    <li class="nav-item dropdown">
                            <a class="nav-link dropdown-toggle" href="http://example.com" data-toggle="dropdown">Welcome {{user.first_name}} {{user.last_name}} </a>
                            <div class="dropdown-menu dropdown-menu-lg-right">
                                <a class="dropdown-item" href="{% url 'accounts:logout'%}">Log out</a>
                                <a class="dropdown-item" href="#">Change Password</a>
                                <!--<a class="dropdown-item" href="#">Indonesia</a> -->
                            </div>
                        </li>
                    {% else %}
                    <li class="nav-item dropdown">
                        <a class="nav-link dropdown-toggle" data-toggle="dropdown" href="#"><i
                                class="fas fa-bars text-muted mr-2"></i>{%trans 'Categories'%}  </a>
                        <div class="dropdown-menu">
                            <a href="{% url 'olretail:index' %}">{% trans 'All'%}</a>
                            {% for category in categories%}
                            <a class="dropdown-item"
                                href="{% url 'olretail:index'%}?category={{category.slug}}">{{category.title}}</a>
                            {% endfor %}
                        </div>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" href="#">{% trans 'Busines & Services'%}</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" href="#">{% trans 'Trade shows'%}</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" href="#">{% trans 'Services'%}</a>
                    </li>
                    
                </ul>
                
                <!-- Right -->
                <ul class="navbar-nav ml-md-auto align-items-start">
                    <li class="nav-item">
                        <a class="nav-link" href="#">{% trans 'Get the app'%}</a>
                    </li>
                    <li class="nav-item dropdown">
                       
                        <a class="nav-link dropdown-toggle" data-toggle="dropdown">{%trans 'Select Languages'%}</a>
                        <div class="dropdown-menu dropdown-menu-lg-right">
                            {% get_current_language as LANGUAGE_CODE %}
                            {% get_available_languages as LANGUAGES %}
                            {% get_language_info_list for LANGUAGES as languages %}
                            {% for language in languages %}
                            {%if language.code == 'tt'%}
                            <a class="dropdown-item" href="/{{ language.code }}{{ request.get_full_path|slice:'3:' }}">Tetum</a>
                            {% else%}
                            <a class="dropdown-item" href="/{{ language.code }}{{ request.get_full_path|slice:'3:' }}">English</a>
                            {% endif %} 
                            {% endfor %}
                          
                    
                        </div>
                    </li>
                </ul>
                {% endif %}

            </div>
            <!-- Links -->

        </div>

    </nav>
    <!-- Navbar -->

</header>

templates/shared/my_market.html
<div class="col-md-4 col-lg-3 col-xl-2">
        <h6>MY MARKETS</h6>
        <ul class="list-group list-group-flush">
                <li class="list-group-item pl-0"><a class="text-grey-dark" href="#">Fashion and
                                clothes</a></li>
                <li class="list-group-item pl-0"><a class="text-grey-dark" href="#">Automobile and
                                motors</a></li>
                <li class="list-group-item pl-0"><a class="text-grey-dark" href="#">Gardening and
                                agriculture</a></li>
                <li class="list-group-item pl-0"><a class="text-grey-dark" href="#">Electronics and
                                tech</a></li>
                <li class="list-group-item pl-0"><a class="text-grey-dark" href="#">Packaginf and
                                printing</a></li>
                <li class="list-group-item pl-0"><a class="text-grey-dark" href="#">Home and kitchen</a>
                </li>
                <li class="list-group-item pl-0"><a class="text-grey-dark" href="#">Digital goods</a>
                </li>
                <li class="list-group-item pl-0 dropdown">
                        <a class="dropdown-toggle" id="navbarDropdownMenuLink" data-toggle="dropdown"
                                aria-haspopup="true" aria-expanded="false">More items</a>
                        <div class="dropdown-menu" aria-labelledby="navbarDropdownMenuLink">
                                <a class="dropdown-item" href="#">Submenu name</a>
                                <a class="dropdown-item" href="#">Great submenu</a>
                                <a class="dropdown-item" href="#">Another menu</a>
                                <a class="dropdown-item" href="#">Some others</a>
                        </div>
                </li>
        </ul>
</div>

templates/shared/navbar.html
{% load static %}
  
  <!-- Navbar -->
<nav class="navbar navbar-expand-lg navbar-light bg-light sticky-top">
    <!-- Container wrapper -->
    <div class="container-fluid">
        <!-- Toggle button -->
        <button class="navbar-toggler" type="button" data-mdb-toggle="collapse"
            data-mdb-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false"
            aria-label="Toggle navigation">
            <i class="fas fa-bars"></i>
        </button>

        <!-- Collapsible wrapper -->
        <div class="collapse navbar-collapse" id="navbarSupportedContent">
            <!-- Navbar brand -->
            <a class="navbar-brand mt-2 mt-lg-0" href="{% url 'index'%}">
                <img src="{% static  'mdb/img/logo_ortl.jpeg'%}" height="35" alt="" loading="lazy" class="bg-image bg-transparent" />
            </a>
            <!-- Left links -->
            <ul class="navbar-nav me-auto mb-2 mb-lg-0">
                <li class="nav-item">
                    <a class="nav-link" href="{%url 'index'%}">Home</a>
                </li>
                <li class="nav-item dropdown">
                        <a class="nav-link dropdown-toggle" href="#" id="navbarDropdownMenuLink" role="button" data-mdb-toggle="dropdown"  aria-expanded="false">
                        Product
                        </a>
                        <ul class="dropdown-menu" aria-labelledby="navbarDropdownMenuLink">
                          <li><a class="dropdown-item" href="#">Informatics</a></li>
                          <li><a class="dropdown-item" href="#">Clothings</a></li>
                          <li><a class="dropdown-item" href="#">Something else here</a></li>
                        </ul>
                      </li>
                <li class="nav-item">
                    <a class="nav-link" href="{% url 'login'%}">Login</a>
                </li>
            </ul>
            <!-- Left links -->
        </div>
        <!-- Collapsible wrapper -->

        <!-- Right elements -->
        <div class="d-flex align-items-center">
            <!-- Icon -->
            <a class="text-reset me-3" href="#">
                <i class="fas fa-shopping-cart"></i>
            </a>

            <!-- Notifications -->
            <a class="text-reset me-3 dropdown-toggle hidden-arrow" href="#" id="navbarDropdownMenuLink" role="button"
                data-mdb-toggle="dropdown" aria-expanded="false">
                <i class="fas fa-bell"></i>
                <span class="badge rounded-pill badge-notification bg-danger">1</span>
            </a>
            <ul class="dropdown-menu dropdown-menu-end" aria-labelledby="navbarDropdownMenuLink">
                <li>
                    <a class="dropdown-item" href="#">Some news</a>
                </li>
                <li>
                    <a class="dropdown-item" href="#">Another news</a>
                </li>
                <li>
                    <a class="dropdown-item" href="#">Something else here</a>
                </li>
            </ul>

            <!-- Avatar -->
            <a class="dropdown-toggle d-flex align-items-center hidden-arrow" href="#" id="navbarDropdownMenuLink"
                role="button" data-mdb-toggle="dropdown" aria-expanded="false">
                <img src="https://mdbootstrap.com/img/new/avatars/2.jpg" class="rounded-circle" height="25" alt=""
                    loading="lazy" />
            </a>
            <ul class="dropdown-menu dropdown-menu-end" aria-labelledby="navbarDropdownMenuLink">
                <li>
                    <a class="dropdown-item" href="#">My profile</a>
                </li>
                <li>
                    <a class="dropdown-item" href="#">Settings</a>
                </li>
                <li>
                    <a class="dropdown-item" href="#">Logout</a>
                </li>
            </ul>
        </div>
        <!-- Right elements -->
    </div>
    <!-- Container wrapper -->
</nav>
<!-- Navbar -->

templates/shared/navbar2.html
<nav class="navbar navbar-expand-lg navbar-light bg-primary mb-1">
    <!-- Container wrapper -->
    <div class="container-fluid">
        <!-- Toggle button -->
        <button class="navbar-toggler" type="button" data-mdb-toggle="collapse"
            data-mdb-target="#navbarLeftAlignExample" aria-controls="navbarLeftAlignExample" aria-expanded="false"
            aria-label="Toggle navigation">
            <i class="fas fa-bars"></i>
        </button>

        <!-- Collapsible wrapper -->
        <div class="collapse navbar-collapse" id="navbarLeftAlignExample">
            <!-- Left links -->
            <ul class="navbar-nav me-auto mb-2 mb-lg-0">
                <li class="nav-item">
                    <a class="nav-link active" aria-current="page" href="#">Categories</a>
                </li>
                <!-- Navbar dropdown -->
                <li class="nav-item dropdown">
                    <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button"
                        data-mdb-toggle="dropdown" aria-expanded="false">
                       Informatics
                    </a>
                    <!-- Dropdown menu -->
                    <ul class="dropdown-menu" aria-labelledby="navbarDropdown">
                        <li>
                            <a class="dropdown-item" href="#">Laptop</a>
                        </li>
                        <li>
                            <a class="dropdown-item" href="#">Ipad</a>
                        </li>
                        <li>
                            <hr class="dropdown-divider" />
                        </li>
                        <li>
                            <a class="dropdown-item" href="#">Tablet</a>
                        </li>
                    </ul>
                </li>
                <!-- Navbar dropdown -->
                <li class="nav-item dropdown">
                    <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button"
                        data-mdb-toggle="dropdown" aria-expanded="false">
                       Clothings
                    </a>
                    <!-- Dropdown menu -->
                    <ul class="dropdown-menu" aria-labelledby="navbarDropdown">
                        <li>
                            <a class="dropdown-item" href="#">Man</a>
                        </li>
                        <li>
                            <a class="dropdown-item" href="#">Woman</a>
                        </li>
                        <li>
                            <hr class="dropdown-divider" />
                        </li>
                    </ul>
                </li>
                  <!-- Navbar dropdown -->
                  <li class="nav-item dropdown">
                        <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button"
                            data-mdb-toggle="dropdown" aria-expanded="false">
                           Furniture
                        </a>
                        <!-- Dropdown menu -->
                        <ul class="dropdown-menu" aria-labelledby="navbarDropdown">
                            <li>
                                <a class="dropdown-item" href="#">Action</a>
                            </li>
                            <li>
                                <a class="dropdown-item" href="#">Another action</a>
                            </li>
                            <li>
                                <hr class="dropdown-divider" />
                            </li>
                            <li>
                                <a class="dropdown-item" href="#">Something else here</a>
                            </li>
                        </ul>
                    </li>
            </ul>
            <!-- Left links -->
        </div>
        <!-- Collapsible wrapper -->
    </div>
    <div class="input-group">
        <div class="form-outline">
            <input type="search" id="form1" class="form-control" />
            <label class="form-label" for="form1">Search</label>
        </div>
        <button type="button" class="btn btn-primary">
            <i class="fas fa-search"></i>
        </button>
    </div>
    <!-- Container wrapper -->
</nav>